### PR TITLE
Quick changes to dev

### PR DESCRIPTION
**Pull request by radu-stefan-dt**
In topology > shared - added missing checks for params not None (missed out this module during initial refactoring)
Formatted the custom exceptions to 4 spaces.

### CODE REVIEW

**Comment by Philipose** [comment]
Are these the right branches intended? This is currently set from dev to master

**Comment by radu-stefan-dt** [comment]
Oh….
I thought I’m pushing dev to dev ?

[cid:image001.png@01D66B75.8C24DCA0]



Best regards,

[dt_logo]
Radu Stefan
Lead Consultant, Dynatrace Services
dynatrace.com<http://www.dynatrace.com>  |  twitter<http://www.twitter.com/dynatrace>  |  LinkedIn<https://www.linkedin.com/company/dynatrace>
M: +44 7564 170293  O: +44 7779 881008
APM Certified Associate
AppMon and NAM Certified Professional
[dt_pro_cert]
[dt_ace_cert]
[ckad_cert]
[aws_cert]
✈ Upcoming annual leave:
📖 Upcoming official training:

**Comment by Philipose** [comment]
Pushing dev to dev wouldn't require a pull request. It's only needed to merge branches. Otherwise you just need to push to that branch

**Comment by radu-stefan-dt** [comment]
pull not needed. will push to dev directly, and we pull & merge to master at next major version release.

**Pull request closed without merging**
